name: slash_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
